# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{codestock}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ongaeshi"]
  s.date = %q{2011-03-11}
  s.description = %q{longer description of your gem}
  s.email = %q{ongaeshi0621@gmail.com}
  s.executables = ["mkgrendb", "grenweb", "grendb", "gren"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/codestock.rb",
    "lib/common/dbdir.rb",
    "lib/common/display_util.rb",
    "lib/common/grenfiletest.rb",
    "lib/common/grensnip.rb",
    "lib/common/platform.rb",
    "lib/common/string_snip.rb",
    "lib/common/util.rb",
    "lib/findgrep/findgrep.rb",
    "lib/findgrep/result.rb",
    "lib/gren.rb",
    "lib/gren/cli.rb",
    "lib/grendb/cli.rb",
    "lib/grenweb/cli.rb",
    "lib/grenweb/database.rb",
    "lib/grenweb/grenweb.ru",
    "lib/grenweb/grep.rb",
    "lib/grenweb/help.rb",
    "lib/grenweb/home.rb",
    "lib/grenweb/html_renderer.rb",
    "lib/grenweb/public/css/gren.css",
    "lib/grenweb/public/images/gren-icon-mini.png",
    "lib/grenweb/public/images/gren-icon.png",
    "lib/grenweb/query.rb",
    "lib/grenweb/searcher.rb",
    "lib/grenweb/viewer.rb",
    "lib/mkgrendb/cli.rb",
    "lib/mkgrendb/cli_old.rb",
    "lib/mkgrendb/grendbyaml.rb",
    "lib/mkgrendb/mkgrendb.rb",
    "test/file_test_utils.rb",
    "test/runner.rb",
    "test/test_dbdir.rb",
    "test/test_gren.rb",
    "test/test_gren_util.rb",
    "test/test_grendbyaml.rb",
    "test/test_grenweb_cli.rb",
    "test/test_grenweb_database.rb",
    "test/test_grenweb_html_renderer.rb",
    "test/test_grenweb_query.rb",
    "test/test_grenweb_searcher.rb",
    "test/test_helper.rb",
    "test/test_mkgrendb.rb",
    "test/test_string_snip.rb"
  ]
  s.homepage = %q{http://github.com/ongaeshi/codestock}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/file_test_utils.rb",
    "test/runner.rb",
    "test/test_dbdir.rb",
    "test/test_gren.rb",
    "test/test_gren_util.rb",
    "test/test_grendbyaml.rb",
    "test/test_grenweb_cli.rb",
    "test/test_grenweb_database.rb",
    "test/test_grenweb_html_renderer.rb",
    "test/test_grenweb_query.rb",
    "test/test_grenweb_searcher.rb",
    "test/test_helper.rb",
    "test/test_mkgrendb.rb",
    "test/test_string_snip.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<termcolor>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<rroonga>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<rack>, [">= 1.2.1"])
      s.add_runtime_dependency(%q<launchy>, [">= 0.3.7"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<termcolor>, [">= 1.2.0"])
      s.add_dependency(%q<rroonga>, [">= 1.0.0"])
      s.add_dependency(%q<rack>, [">= 1.2.1"])
      s.add_dependency(%q<launchy>, [">= 0.3.7"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<termcolor>, [">= 1.2.0"])
    s.add_dependency(%q<rroonga>, [">= 1.0.0"])
    s.add_dependency(%q<rack>, [">= 1.2.1"])
    s.add_dependency(%q<launchy>, [">= 0.3.7"])
  end
end

